//! Code generation for typed identity providers.
//!
//! Given the [`PrincipalContract`](crate::model::PrincipalContract) the
//! compiler derives from a policy set, emit a typed identity struct in Rust
//! or Scala. The generated Rust type implements
//! `policast_datafusion::PrincipalProvider`; the Scala type exposes a
//! `principalBindings` map for the Spark plugin. This closes the loop: the
//! policies declare which principal attributes they need, and the generated
//! provider is the compile-checked contract an integrator fills in.

use crate::model::PrincipalContract;

/// Target language for [`render_identity`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IdentityLang {
    Rust,
    Scala,
}

impl IdentityLang {
    pub fn parse(s: &str) -> Option<Self> {
        match s.to_ascii_lowercase().as_str() {
            "rust" => Some(IdentityLang::Rust),
            "scala" => Some(IdentityLang::Scala),
            _ => None,
        }
    }
}

/// Render a typed identity provider for `contract` in the target language.
pub fn render_identity(lang: IdentityLang, contract: &PrincipalContract) -> String {
    match lang {
        IdentityLang::Rust => render_rust(contract),
        IdentityLang::Scala => render_scala(contract),
    }
}

fn render_rust(contract: &PrincipalContract) -> String {
    let attrs = &contract.required_attributes;
    let mut out = String::new();
    out.push_str("// Generated by `policast gen-identity`. Do not edit by hand.\n");
    out.push_str("use std::collections::BTreeMap;\n\n");
    out.push_str("use policast_datafusion::PrincipalProvider;\n\n");
    out.push_str("/// Identity derived from the compiled manifest's principal contract.\n");
    out.push_str("#[derive(Debug, Clone, Default)]\n");
    out.push_str("pub struct GeneratedIdentity {\n");
    for attr in attrs {
        out.push_str(&format!("    pub {}: Option<String>,\n", rust_ident(attr)));
    }
    out.push_str("}\n\n");

    out.push_str("impl PrincipalProvider for GeneratedIdentity {\n");
    out.push_str("    fn attribute(&self, name: &str) -> Option<String> {\n");
    out.push_str("        match name {\n");
    for attr in attrs {
        out.push_str(&format!(
            "            {:?} => self.{}.clone(),\n",
            attr,
            rust_ident(attr)
        ));
    }
    out.push_str("            _ => None,\n");
    out.push_str("        }\n");
    out.push_str("    }\n\n");
    out.push_str("    fn principal_attributes(&self) -> BTreeMap<String, String> {\n");
    out.push_str("        let mut attrs = BTreeMap::new();\n");
    for attr in attrs {
        out.push_str(&format!(
            "        if let Some(v) = &self.{} {{\n            attrs.insert({:?}.to_string(), v.clone());\n        }}\n",
            rust_ident(attr),
            attr
        ));
    }
    out.push_str("        attrs\n");
    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

fn render_scala(contract: &PrincipalContract) -> String {
    let attrs = &contract.required_attributes;
    let mut out = String::new();
    out.push_str("// Generated by `policast gen-identity`. Do not edit by hand.\n");
    out.push_str("package com.policast.spark.generated\n\n");
    out.push_str("/** Identity derived from the compiled manifest's principal contract. */\n");
    out.push_str("case class GeneratedIdentity(\n");
    let field_lines: Vec<String> = attrs
        .iter()
        .map(|a| format!("    {}: Option[String] = None", scala_ident(a)))
        .collect();
    out.push_str(&field_lines.join(",\n"));
    out.push_str("\n) {\n");
    out.push_str("  def principalBindings: Map[String, String] =\n");
    out.push_str("    Seq(\n");
    let binding_lines: Vec<String> = attrs
        .iter()
        .map(|a| format!("      {}.map({:?} -> _)", scala_ident(a), a))
        .collect();
    out.push_str(&binding_lines.join(",\n"));
    out.push_str("\n    ).flatten.toMap\n");
    out.push_str("}\n");
    out
}

/// Sanitize an attribute name into a valid Rust identifier.
fn rust_ident(attr: &str) -> String {
    sanitize_ident(attr)
}

/// Sanitize an attribute name into a valid Scala identifier.
fn scala_ident(attr: &str) -> String {
    sanitize_ident(attr)
}

fn sanitize_ident(attr: &str) -> String {
    let mut s: String = attr
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    if s.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(true) {
        s.insert(0, '_');
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    fn contract() -> PrincipalContract {
        PrincipalContract {
            required_attributes: vec![
                "name".to_string(),
                "region".to_string(),
                "role".to_string(),
            ],
        }
    }

    #[test]
    fn test_lang_parse() {
        assert_eq!(IdentityLang::parse("Rust"), Some(IdentityLang::Rust));
        assert_eq!(IdentityLang::parse("scala"), Some(IdentityLang::Scala));
        assert_eq!(IdentityLang::parse("go"), None);
    }

    #[test]
    fn test_rust_codegen_has_fields_and_impl() {
        let code = render_identity(IdentityLang::Rust, &contract());
        assert!(code.contains("pub struct GeneratedIdentity"));
        assert!(code.contains("pub role: Option<String>,"));
        assert!(code.contains("pub region: Option<String>,"));
        assert!(code.contains("pub name: Option<String>,"));
        assert!(code.contains("impl PrincipalProvider for GeneratedIdentity"));
        assert!(code.contains("\"role\" => self.role.clone(),"));
        assert!(code.contains("fn principal_attributes"));
    }

    #[test]
    fn test_scala_codegen_has_case_class_and_bindings() {
        let code = render_identity(IdentityLang::Scala, &contract());
        assert!(code.contains("case class GeneratedIdentity("));
        assert!(code.contains("role: Option[String] = None"));
        assert!(code.contains("def principalBindings: Map[String, String]"));
        assert!(code.contains("role.map(\"role\" -> _)"));
    }

    #[test]
    fn test_sanitize_ident() {
        assert_eq!(sanitize_ident("role"), "role");
        assert_eq!(sanitize_ident("cost-center"), "cost_center");
        assert_eq!(sanitize_ident("2fa"), "_2fa");
    }

    #[test]
    fn test_empty_contract_rust_still_valid_shape() {
        let code = render_identity(IdentityLang::Rust, &PrincipalContract::default());
        assert!(code.contains("pub struct GeneratedIdentity"));
        assert!(code.contains("_ => None,"));
    }
}
